name: 'healthy gas data'
train_test_split:
  # can be any attribute of the BatteryData object. Values listed here will be EXCLUDED.
  battery_filters: 
    has_gas: 
      - False
    is_healthy:
      - False

  # any Timeseries data with any of the following terms in its description will be EXCLUDED.
  timeseries_filter: 
    - '4'
    - '5'